Add go lint and go vet

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -14,13 +14,64 @@ gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
 [ -z "$gofiles" ] && exit 0
 
 unformatted=$(gofmt -l $gofiles)
-[ -z "$unformatted" ] && exit 0
 
-# Some files are not gofmt'd. Print message and fail.
+if [[ ! -z "$unformatted" ]]; then
+  printf "Go files must be formatted with gofmt. Please run:"
+  # Some files are not gofmt'd. Print message and fail.
+  for file in $unformatted; do
+    printf "\t\033[31mgofmt -w $file\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
+  done
+  exit 1
+fi
 
-echo >&2 "Go files must be formatted with gofmt. Please run:"
-for fn in $unformatted; do
-	echo >&2 "  gofmt -w $PWD/$fn"
+printf "\t\033[32mgofmt\033[0m \033[0;30m\033[42mpass\033[0m\n"
+
+GOLINT=$GOPATH/bin/golint
+GOIMPORTS=$GOPATH/bin/goimports
+
+# Check for golint
+if [[ ! -x "$GOLINT" ]]; then
+  printf "\t\033[41mPlease install golint\033[0m (go get -u golang.org/x/lint/golint)"
+  exit 1
+fi
+
+# Check for goimports
+if [[ ! -x "$GOIMPORTS" ]]; then
+  printf "\t\033[41mPlease install goimports\033[0m (go get golang.org/x/tools/cmd/goimports)"
+  exit 1
+fi
+
+PASS=true
+
+for FILE in $gofiles
+do
+  # Run goimports on the staged file
+  $GOIMPORTS -w $FILE
+
+  # Run golint on the staged file and check the exit status
+  $GOLINT "-set_exit_status" $FILE
+  if [[ $? == 1 ]]; then
+    printf "\t\033[31mgolint $FILE\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
+    PASS=false
+  else
+    printf "\t\033[32mgolint $FILE\033[0m \033[0;30m\033[42mpass\033[0m\n"
+  fi
+
+  # Run govet on the staged file and check the exit status
+  go vet $FILE
+  if [[ $? != 0 ]]; then
+    printf "\t\033[31mgo vet $FILE\033[0m \033[0;30m\033[41mFAILURE!\033[0m\n"
+    PASS=false
+  else
+    printf "\t\033[32mgo vet $FILE\033[0m \033[0;30m\033[42mpass\033[0m\n"
+  fi
 done
 
-exit 1
+if ! $PASS; then
+  printf "\033[0;30m\033[41mCOMMIT FAILED\033[0m\n"
+  exit 1
+else
+  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
+fi
+
+exit 0
